#' Enhanced PCA Plot with Variance Explained
#'
#' @description
#' A wrapper around `SCpubr::do_DimPlot()` specifically designed for PCA plots that
#' automatically adds variance explained percentages to the axis labels.
#'
#' @param sample Seurat object, generated by CreateSeuratObject.
#' @param dims numeric. Vector of 2 numerics indicating the PC dimensions to plot.
#'   Defaults to c(1, 2).
#' @param group.by character. Metadata variable to group the output by.
#'   Has to be a character or factor column.
#' @param split.by character. Secondary metadata variable to further group (split)
#'   the output by. Has to be a character or factor column.
#' @param colors.use named_vector. Named vector of valid color representations
#'   with as many named colors as unique values of group.by.
#' @param variance_digits numeric. Number of decimal places for variance percentages.
#'   Defaults to 1.
#' @param ... Additional arguments passed to `SCpubr::do_DimPlot()`.
#'
#' @return ggplot2 object with PCA plot including variance explained in axis labels.
#'
#' @examples
#' \dontrun{
#' # Basic PCA plot with variance explained
#' do_PcaPlot(seurat_object, group.by = "condition")
#'
#' # Plot specific PC dimensions
#' do_PcaPlot(seurat_object, dims = c(2, 3), group.by = "cluster")
#'
#' # With custom colors
#' colors <- c("Control" = "#2E86AB", "Treatment" = "#A23B72")
#' do_PcaPlot(seurat_object, group.by = "condition", colors.use = colors)
#' }
#'
#' @export
do_PcaPlot <- function(
    sample,
    dims = c(1, 2),
    group.by = NULL,
    split.by = NULL,
    colors.use = NULL,
    variance_digits = 1,
    ...
) {

  # Input validation
  if (!inherits(sample, "Seurat")) {
    stop("sample must be a Seurat object")
  }

  if (!"pca" %in% names(sample@reductions)) {
    stop("PCA reduction not found in Seurat object. Please run RunPCA() first.")
  }

  if (length(dims) != 2) {
    stop("dims must be a vector of length 2")
  }

  if (!is.numeric(dims) || any(dims < 1)) {
    stop("dims must be positive integers")
  }

  # Check if requested dimensions exist
  max_pc <- ncol(sample@reductions$pca@cell.embeddings)
  if (any(dims > max_pc)) {
    stop(paste("Requested PC dimensions exceed available PCs. Maximum PC:", max_pc))
  }

  # Calculate variance explained for all PCs
  pca_stdev <- sample@reductions$pca@stdev
  total_variance <- sum(pca_stdev^2)
  variance_explained <- (pca_stdev^2 / total_variance) * 100

  # Get variance for requested dimensions
  pc1_var <- variance_explained[dims[1]]
  pc2_var <- variance_explained[dims[2]]

  # Format variance labels
  pc1_label <- paste0("PC", dims[1], " (", round(pc1_var, variance_digits), "%)")
  pc2_label <- paste0("PC", dims[2], " (", round(pc2_var, variance_digits), "%)")

  # Create base plot using do_DimPlot
  plot <- SCpubr::do_DimPlot(
    sample = sample,
    reduction = "pca",
    dims = dims,
    group.by = group.by,
    split.by = split.by,
    colors.use = colors.use,
    plot.axes = TRUE,
    ...
  )

  # Add variance explained to axis labels
  plot <- plot +
    ggplot2::labs(
      x = pc1_label,
      y = pc2_label
    )

  return(plot)
}

#' Get PCA Variance Explained Summary
#'
#' @description
#' Helper function to extract variance explained information from a Seurat object.
#'
#' @param sample Seurat object with PCA reduction.
#' @param n_pcs numeric. Number of top PCs to return. If NULL, returns all PCs.
#'
#' @return data.frame with PC number, variance explained percentage, and cumulative variance.
#'
#' @examples
#' \dontrun{
#' # Get variance for first 10 PCs
#' get_pca_variance(seurat_object, n_pcs = 10)
#'
#' # Get variance for all PCs
#' get_pca_variance(seurat_object)
#' }
#'
#' @export
get_pca_variance <- function(sample, n_pcs = NULL) {

  # Input validation
  if (!inherits(sample, "Seurat")) {
    stop("sample must be a Seurat object")
  }

  if (!"pca" %in% names(sample@reductions)) {
    stop("PCA reduction not found in Seurat object. Please run RunPCA() first.")
  }

  # Calculate variance explained
  pca_stdev <- sample@reductions$pca@stdev
  total_variance <- sum(pca_stdev^2)
  variance_explained <- (pca_stdev^2 / total_variance) * 100

  # Create summary data frame
  variance_df <- data.frame(
    PC = 1:length(variance_explained),
    variance_explained = variance_explained,
    cumulative_variance = cumsum(variance_explained)
  )

  # Subset if n_pcs specified
  if (!is.null(n_pcs)) {
    if (!is.numeric(n_pcs) || n_pcs < 1) {
      stop("n_pcs must be a positive integer")
    }
    if (n_pcs > nrow(variance_df)) {
      warning(paste("n_pcs exceeds available PCs. Returning all", nrow(variance_df), "PCs."))
    } else {
      variance_df <- variance_df[1:n_pcs, ]
    }
  }

  return(variance_df)
}

#' Enhanced UMAP Plot with Preferred Settings
#'
#' @description
#' A wrapper around `SCpubr::do_DimPlot()` specifically designed for UMAP plots with
#' optimized default settings for axes and labels.
#'
#' @param sample Seurat object, generated by CreateSeuratObject.
#' @param dims numeric. Vector of 2 numerics indicating the UMAP dimensions to plot.
#'   Defaults to c(1, 2).
#' @param group.by character. Metadata variable to group the output by.
#'   Has to be a character or factor column.
#' @param split.by character. Secondary metadata variable to further group (split)
#'   the output by. Has to be a character or factor column.
#' @param colors.use named_vector. Named vector of valid color representations
#'   with as many named colors as unique values of group.by.
#' @param plot.axes logical. Whether to plot axes. Defaults to TRUE.
#' @param label logical. Whether to plot cluster labels. Defaults to TRUE.
#' @param label.size numeric. Size of the labels. Defaults to 4.
#' @param label.color character. Color of the labels. Defaults to "black".
#' @param label.fill character. Color to fill the labels. Defaults to "white".
#' @param pt.size numeric. Size of the dots. Defaults to 1.
#' @param ... Additional arguments passed to `SCpubr::do_DimPlot()`.
#'
#' @return ggplot2 object with UMAP plot using preferred settings.
#'
#' @examples
#' \dontrun{
#' # Basic UMAP plot with preferred settings
#' do_UmapPlot(seurat_object, group.by = "condition")
#'
#' # With custom colors
#' colors <- c("Control" = "#2E86AB", "Treatment" = "#A23B72")
#' do_UmapPlot(seurat_object, group.by = "condition", colors.use = colors)
#'
#' # Without labels
#' do_UmapPlot(seurat_object, group.by = "condition", label = FALSE)
#' }
#'
#' @export
do_UmapPlot <- function(
    sample,
    dims = c(1, 2),
    group.by = NULL,
    split.by = NULL,
    colors.use = NULL,
    plot.axes = TRUE,
    label = TRUE,
    label.size = 4,
    label.color = "black",
    label.fill = "white",
    pt.size = 1,
    ...
) {

  # Input validation
  if (!inherits(sample, "Seurat")) {
    stop("sample must be a Seurat object")
  }

  if (!"umap" %in% names(sample@reductions)) {
    stop("UMAP reduction not found in Seurat object. Please run RunUMAP() first.")
  }

  if (length(dims) != 2) {
    stop("dims must be a vector of length 2")
  }

  if (!is.numeric(dims) || any(dims < 1)) {
    stop("dims must be positive integers")
  }

  # Check if requested dimensions exist
  max_dim <- ncol(sample@reductions$umap@cell.embeddings)
  if (any(dims > max_dim)) {
    stop(paste("Requested UMAP dimensions exceed available dimensions. Maximum dimension:", max_dim))
  }

  # Create UMAP labels
  umap1_label <- paste0("UMAP", dims[1])
  umap2_label <- paste0("UMAP", dims[2])

  # Create base plot using do_DimPlot
  plot <- SCpubr::do_DimPlot(
    sample = sample,
    reduction = "umap",
    dims = dims,
    group.by = group.by,
    split.by = split.by,
    colors.use = colors.use,
    plot.axes = plot.axes,
    label = label,
    label.size = label.size,
    label.color = label.color,
    label.fill = label.fill,
    pt.size = pt.size,
    ...
  )

  # Add standard UMAP axis labels
  plot <- plot +
    ggplot2::labs(
      x = umap1_label,
      y = umap2_label
    )

  return(plot)
}

